#!/usr/bin/env bash

# Exit on error.
set -e

# Get our working directory, since it will be random.
HERE="$(readlink -f "$(dirname "$0")")"

# Set up PATH environment variable to prefer executables from AppImage.
export PATH="${HERE}/usr/bin:${PATH}"

# Find the name of the program, and, if custom, verify its existence.
EXE=""
if test ! -z "${APPIMAGE_EXE}"; then
  if test -x "${HERE}/usr/bin/${APPIMAGE_EXE}"; then
    EXE="${HERE}/usr/bin/${APPIMAGE_EXE}"
  elif test "${APPIMAGE_EXE}" = "list"; then
    find "${HERE}/usr/bin" -type f -executable -exec basename {} ';'
    exit 0
  else
    echo "ERROR: Program '${APPIMAGE_EXE}' not found in AppImage." >&2
    exit 1
  fi
elif test ! -z "${1}" && test -x "${HERE}/usr/bin/${1}"; then
  # Multi-call format (qemu.AppImage qemu-img ...)
  # This format shouldn't allow 'list', in case some program also uses that.
  # APPIMAGE_EXE usage should also continue to override this, if set.
  EXE="${HERE}/usr/bin/${1}"
  # Shift arguments on account of first argument being program name.
  shift
fi
if test -z "$EXE"; then
  # No custom program was set, so default to 'qemu-system-x86_64'.
  # It is expected behaviour for this to be the default even on non-x86_64.
  EXE="${HERE}/usr/bin/qemu-system-x86_64"
fi

# If it is a 'qemu-system' binary, run with -L to set runtime path.
if basename "${EXE}" | grep -q "^qemu-system"; then
  exec "${EXE}" -L "${HERE}/usr/share/qemu" "$@"
else
  exec "${EXE}" "$@"
fi
